### ISSUE TITLE
File browser dialog does not appear

### ISSUE THREAD

**Issue by natemurthy** [Serhioromano/angular-aws-s3-upload#8]
I cloned your repository and installed all the dependencies. But when I click on the "Select file" button nothing happens. Am I missing some detail of how the s3 angular controller should behave?

**Comment by gcmartins93** [comment]
Try using a div element instead of a button, worked for me. So, instead of:

`<button class="btn btn-default" s3 options="options" name="uploads" ng-model="form.files" required> Select File </button>`

use:

`<**div** class="btn btn-default" s3 options="options" name="uploads" ng-model="form.files" required> Select File </div>`

**Comment by Serhioromano** [comment]
What is your browser?
